---
- name: '[dependencies] Update packages on Debian'
  apt:
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Debian'

- name: '[dependencies] Install packages including Ralink firmware, usbutils, isc-dhcp-server, hostapd'
  package:
    name:
    - usbutils
    - firmware-misc-nonfree
    #- firmware-ralink
    - isc-dhcp-server
    - hostapd
    state: latest
  become: yes
  tags:
  - wifi_ap
  - wifi_ap_dependencies

- name: '[dependencies] Install iptables-persistent'
  package: name=iptables-persistent state=present
  register: wifi_ap_iptables_install
  notify: '[wifi_ap] Reboot the host'
  become: yes
  tags:
  - wifi_ap
  - wifi_ap_dependencies
...
