---
- name: '[dependencies] Install packages including Ralink firmware, usbutils, isc-dhcp-server, hostapd'
  package:
    name:
    - usbutils
    - firmware-ralink
    - isc-dhcp-server
    - hostapd
    state: latest
  become: yes
  tags:
    - minibian_ap
    - minibian_ap_dependencies

- name: '[dependencies] Install iptables-persistent'
  package: name=iptables-persistent state=present
  register: minibian_ap_iptables_install
  become: yes
  tags:
    - minibian_ap
    - minibian_ap_dependencies

# haven't find a solution without reboot
# Although the reboot happens we still need all handlers to be run
- name: Reboot the managed host to reload iptables kernel modules
  shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
  async: 1
  poll: 0
  become: yes
  when: minibian_ap_iptables_install.changed
  tags:
    - minibian_ap
    - minibian_ap_dependencies

# ansible_ssh_host variable is set in ansible inventory (hosts) file
- name: Waiting for managed host to come back after reboot
  local_action:
    module: wait_for
      host="{{ ansible_ssh_host }}"
      port=22
      delay=1
  become: no
  when: minibian_ap_iptables_install.changed
  tags:
    - minibian_ap
    - minibian_ap_dependencies
...
